services:
  - type: web
    name: factcheck-prototype
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: YANDEX_USER
        sync: false
      - key: YANDEX_KEY
        sync: false
      - key: YANDEX_L10N
        value: ru
      - key: YANDEX_SORTBY
        value: rlv
      - key: YANDEX_FILTER
        value: strict
      - key: YANDEX_RESULTS
        value: "5"